### ISSUE TITLE
Parsing attributes containing the string "]]>" raise an error

### ISSUE THREAD

**Issue by DrRataplan** [lddubeau/saxes#1]
Hi,

When I run the following code snippet in the browser: `new DOMParser().parseFromString('<e attr="]]>"></e>', 'text/xml')`. It outputs an element with an attribute set to `]]>`. When I serialize it again, I get `<e attr="]]&gt;"></e>`.

However, when I try to parse the same string with saxes, I get an error.

[The spec](https://www.w3.org/TR/xml/#syntax) mentions that the `]]>` sequence MUST be escaped as `]]&gt;` because of compatibility with SGML. However, that only seems to count for serializing XML. Also, all of the parsers I've tried accept this string.

Should saxes really throw an error?

**Comment by lddubeau** [comment]
Thank you for the report. Yes, there is a bug in saxes: `]]>` should be allowed as-is *in attributes*.

However, `]]>` is not allowed as-is in `CharData`. Try parsing `<foo>]]></foo>` with `xmllint`. You'll get an error because of `]]>`. My mistake was to think that the prohibition applied also in attributes. I looked again at the prose description and find it a bit confusing. The paragraph starts with conditions that pertain everywhere but in the last clause of the last sentence there's a condition that pertains only to element content. However, I reviewed the relevant productions (`CharData`, `content` and `AttValue`) and find that they clearly show my understanding was wrong.

A fix should be coming soon.
