### ISSUE TITLE
onprocessinginstruction event not firing for XML Declaration

### ISSUE THREAD

**Issue by kenlyon** [lddubeau/saxes#16]
I'm using [jsdom](https://github.com/jsdom/jsdom) to parse XML into a DOM and then serialize it back after I make some modifications to it.

I noticed that the _processing instruction_ was missing from the top of the serialized output. At first, I thought this was a limitation of the module. However, it seems that it tries to use the _onprocessinginstruction_ event from saxes, but it's not fired in my case.

I can see in the `sPIEnding()` method that it is fired from the second `if` clause, but in my case`piIsXMLDecl` is `true`, so the event is not fired. Is this the intended behaviour?

My xml file starts with the standard processing instruction of:
`<?xml version="1.0" encoding="UTF-8"?>`

**Comment by kenlyon** [comment]
OK, so I just read on Wikipedia that the XML Declaration is not a processing instruction:
https://en.wikipedia.org/wiki/Processing_Instruction

I think my question should be "Should I expect saxes to create a node for the XML declaration? If so, is there anything special that I'm missing to make it work?"

**Comment by lddubeau** [comment]
Yep, it's an XML declaration. 

Saxes does not have an event specifically for the XML declaration. The README mentions:

> `xmlDecl` - The XML declaration for this document. It contains the fields
`version`, `encoding` and `standalone`. They are all `undefined` before
encountering the XML declaration. If they are undefined after the XML
declaration, the corresponding value was not set by the declaration. There is no
event associated with the XML declaration. In a well-formed document, the XML
declaration may be preceded only by an optional BOM. So by the time any event
generated by the parser happens, the declaration has been processed if present
at all. Otherwise, you have a malformed document, and as stated above, you
cannot rely on the parser data!

----

Looking at the code in jsdom, I don't see that any care has been taken there to read `xmlDecl` and populate the corresponding fields. And doing a quick test with Chrome and Firefox, I see no consistency in how the XML declaration is handled. I tried this:

```
d = new DOMParser().parseFromString(`<?xml version="1.0" encoding="ascii"?><foo></foo>`, "text/xml")
```

In Chrome, `d` has an `xmlEncoding` field set to `"ascii"`. In Firefox, there's no such field, and I don't see any equivalent. I've also tried `new XMLSerializer().serializeToString(d)`. Chrome created an XML declaration equivalent to the original. Firefox produced a declaration with `encoding="UTF-8"`.

My recollection is that the last time I considered the support for XML declarations in DOM trees there was no specification. I think this is still the case. If so, then jsdom just ignoring it is not *wrong*.

**Comment by kenlyon** [comment]
Thanks for your response. I've logged [jsdom issue #2615](https://github.com/jsdom/jsdom/issues/2615) to follow up with them. I think you're correct that it's not strictly wrong on their part, but it would be handy to have the ability to retain the declaration when re-serializing.

**Comment by kenlyon** [comment]
I did an experiment in `jsdom` and found that if I inspect `parser.xmlDecl` after `parser.write()` but before `parser.close()` then it does indeed contain the values that were present in the xml file.

There isn't a bug here in `saxes`, as this is the appropriate place to find these details rather than the `onprocessinginstruction` event.

Thanks for your help in explaining it to me!

**Comment by wvbe** [comment]
I'm running into trouble tracking the position for the first node following the XML declaration.

So far what has been successful is recording the position on every emitted node event, and so the next node must have started at the previously recorded position in string and ends at the current position. If the XML document starts with an XML declaration however, the range for the first emitted node (either a doctype, PI or element) erroneously includes the XML declaration too.

Would it make sense to invent a new event? `onxmldeclaration` for example? Or is there a cleaner way in which an update to the position tracking can be emitted?

Totally prepared to make a PR for this but given the above discussion I'm unsure if this should be fixed in `saxes`, `jsdom` or otherwise. If I'm not commenting into the void (since the issue is closed), please let me know!

Best,
Wybe

**Comment by lddubeau** [comment]
@wvbe Can you open a new issue? There's definitely something to discuss but it might need more than an event. Also, if you have a minimal code example of the approach you are using, it would be good. I think I know what you are doing but code would help make sure that I'm understanding correctly.

**Comment by wvbe** [comment]
Thanks @lddubeau 
Created #30
