### ISSUE TITLE
Edge: error on import

### ISSUE THREAD

**Issue by Christilut** [lddubeau/saxes#27]
There seems to a small issue on Edge. I'm getting the following error:
`SCRIPT1028: SCRIPT1028: Expected identifier, string or number`

Edge gives the most helpful errors.. It claims to break on this line: `this.ns = { __proto__: null, ...rootNS };` but who knows if that's really true.

After removing the import statement `import * as Saxes from 'saxes'`, the error is gone. I can't really debug further than that.

I'm using the vue-cli, so webpack.

**Comment by Christilut** [comment]
I guess it's [object destructuring](https://caniuse.com/#feat=mdn-javascript_operators_destructuring_rest_in_objects)...

**Comment by lddubeau** [comment]
Thank you for the bug report and the PR.

Some thoughts, in no specific order:

1. A Chromium-based Edge is going to be released on Jan 15th. From that point on, supporting the latest version of Edge will cost almost nothing extra relative to supporting Chrome.

2. If we're going to modify the code so that saxes runs in Edge, then the test suite should be run in Edge too to make sure regressions don't happen. Next week I may add something that depends on a language feature that Edge does not support (or accept a PR that does the same), and break things again.

   This is also necessary to ensure that saxes does not run into issues that are detectable only by executing the code. The error you ran into happened at the time of parsing the JavaScript code, prior to executing it, but some errors (e.g. a missing method on `String`) are not detectable until the problematic code is actually executed, and some errors are not detectable until problematic code is executed with specific data. The suite covers a broad range of cases.

   If I were to implement this, I'd setup something with Karma and BrowserStack to launch an instance of Edge and run the test suite (or run as much of the suite as possible; there may be some tests that cannot run in a browser).

**Comment by Christilut** [comment]
I agree. I'd just wait it out until the 15th. I've put a message on my website for users explaining that and that Edge isn't supported until then.
Even after I changed saxes to work, Edge didn't support other basic features so I decided to just not support it.
