### ISSUE TITLE
Event that the position tracking offset was updated not given for XML declaration

### ISSUE THREAD

**Issue by wvbe** [lddubeau/saxes#30]
I am trying to track the XML substring for any given node parsed to a DOM document and saxes position tracking. I am trying to achieve this by creating a DOM as saxes emits new nodes, and diffing the tracked positions at those events. This works well if an event is given any time the position offset is updated in the parser. The issue I run in to is that the XML declaration does not give me an event because it is not a DOM node. This robs me of the offset at which the first emitted node is found.

----

If you (`npm i saxes slimdom` and) run the following:

```

const saxes = require('saxes');
const slimdom = require('slimdom');

const parser = new saxes.SaxesParser({
	position: true
});

function getDocumentWithStartAndEndPositionsPerNode (xmlString) {
	const document = new slimdom.Document();
	let nextNodeParentNode = document;

	// By keeping track of the last parser position you can tell what the XML source ubstring for the last created DOM
	// node is.
	let nextNodeStartPosition = parser.position;

	parser.oncomment = (comment) => {
		const node = document.createComment(comment);
		nextNodeParentNode.appendChild(node);

		// Set the offsets for the XML substring for this node
		node.stringStartOffset = nextNodeStartPosition;
		node.stringEndOffset = parser.position + nextNodeStartPosition;
		nextNodeStartPosition = parser.position;
	};

	parser.onopentag = (element) => {
		const node = document.createElement(element.name);

		// Set the offset for the XML substring for this node
		node.stringStartOffset = nextNodeStartPosition;
		nextNodeStartPosition = parser.position;

		nextNodeParentNode.appendChild(node);
		nextNodeParentNode = node;
	},

	parser.onclosetag = () => {
		nextNodeParentNode = nextNodeParentNode.parentNode;

		// Set the offset for the XML substring for this node
		nextNodeParentNode.stringEndOffset = parser.position;
		nextNodeStartPosition = parser.position;
	},

	parser.write(xmlString).close();

	return document;
}

console.log('Happy flow without XML declaration:');
const dom1 = getDocumentWithStartAndEndPositionsPerNode('<!--test--><x />');
console.log(dom1.childNodes[0].stringStartOffset); // Offset for comment, is correct
console.log(dom1.childNodes[1].stringStartOffset); // Offset for element, is correct

console.log('Error with XML declaration:');
const dom2 = getDocumentWithStartAndEndPositionsPerNode('<?xml version="1.0"?><!--test--><x />');
console.log(dom2.childNodes[0].stringStartOffset); // Offset for comment, is erroneous because nextNodeStartPosition was
                                                   // not updated after encountering XML declaration
console.log(dom2.childNodes[1].stringStartOffset); // Offset for element, is correct
```

In the first console log, `0` and `11` are expected because the comment starts at `0` and is `11` chars long.

In the second console log `21` and `32` are expected because the XML declaration is 21 characters long. However `0` and `32` are found because the "start" for the first emitted node was not set right.

(Actual results are 1 lower because of some offset thing, I think that's unrelated)

----

As for a solution, either an emitted event that the XML declaration PI has finished parsing would do (and `parser.position` is updated) or a way to find how much characters were in the XML declaration.

Let me know what I can do! Or if I can clarify anything about the above

**Comment by lddubeau** [comment]
Thank you. That's very useful.

The position issue is bigger than just dealing with XML declarations. Take your first example, and add spaces before and after the comment. Your resulting positions won't be correct anymore. The reason is that the only non-markup text that can appear outside the top level element is spaces, and these spaces are not significant as far as XML is concerned. So saxes does not emit any events for them.

The position logic is the one area that I've not improved much since the fork from sax. Saxes probably does a bit of a better job than sax reporting sensible positions but it could be much more useful. The thought has occurred to me once in a while that maybe the objects passed to the event handlers should contain the extents (start and end position) of the corresponding feature in the data being parsed. I'm thinking that's what would be needed to allow doing what you are trying to do and nail it once and for all.

**Comment by wvbe** [comment]
@lddubeau, thank you for your response. You are right, adding those spaces breaks my idea same as XML declarations do.

The approach as per your last remark makes a lot of sense, more so than (the current implementation and) my own sauce on top of the parser.

To clarify, did you envision an API like so?

```
parser.oncomment = (comment, position) => {
  // ...
};
```

If so, other questions I have are:
- In your opinion, what would be appropriate property names within a "position" object?
- Is it intentional that `.column' starts at 0, whereas `.line` and I think most column numbers in other software start at 1?

Again, many thanks for your time

Wybe

**Comment by lddubeau** [comment]
Initially I was thinking of including position information into the objects that are passed to the event handlers, but I'm thinking passing an extent as an additional parameter like you suggest is probably better.

I've not thought yet about the names of the fields. I'm thinking what is needed are extents recording the start and end of a feature:

```
{ 
  start: { column: 0, line: 1, position: 0 },
  end: { column: 10, line: 1, position: 10 },
}
```

(Note the term "position" is already used by saxes to refer to the current position into the stream of characters *as a whole*. It is probably not used that often in practice, but it is there.)

I would set the logic so that these objects are created only if the parser's options require position tracking. It is possible to turn position tracking off already, though currently it only affects the error messages. That is, it is only cosmetic. There's currently no performance benefit to updating the internal fields that track position *only* if it position tracking is requested: checking the flag is about as time-consuming as just doing it whether the flag is on or off.

Actually, as I'm writing this I'm thinking there should be a different flag to determine whether the extents are created and passed to the event handlers. I could see situations where someone wants errors to have line and column numbers but *still* not want to pay the cost of getting extents generated with every event. (This is my case in almost every situation.)

Probably systems in which both line and column numbers are one-based are the most popular. However, systems with one-based lines and zero-based columns are out there. One prominent one is Emacs, which I happen to use as my main editor/IDE. As far as I can tell from quickly looking at the latest version of sax-js, sax-js is zero-based for both line and column. I'm afraid I don't have a record of why saxes become one-based for lines. Maybe I ran into a situation while I was forking sax-js where zero-based lines were a problem and I changed it to be one-based. Given my acquaintance with Emacs, I may not have felt that having columns remain zero-based was particularly objectionable.

----

In the off-chance you are thinking of submitting a PR, you should know that I'm in the midst of converting saxes' code to TypeScript. So I'd hold off on a PR until that conversion is done.

saxes supports TypeScript already but I've gotten tired of maintaining a separate hand-created `saxes.d.ts` file because: a) it is error prone (I discovered some errors in `saxes.d.ts` during the current conversion work), b) because they are an afterthought, the typings in the `.d.ts` file are not as well designed as they should be.

**Comment by wvbe** [comment]
Hey @lddubeau, good and timely remarks ;)

The extend object as you posted it looks great, it has all information anyone would need in there and even avoids an itch I had with putting everything in one object. Great.

I'm fine with using 0-based column numbers, the workaround for any consumer is simple enough.

I am indeed thinking of submitting a PR although I'll need some time to get in to it and there is no urgency for me. I'll hold off on that and look forward to shiny TS code :) Closing this issue now because it has been determined this is not a bug.

Thank you for your response and for putting so much work in this lib!

**Comment by lddubeau** [comment]
@wvbe I figure I should update you on the latest.

I've done the changes to saxes I had mentioned earlier, and perhaps a few more. I've listed them in this [comment](https://github.com/lddubeau/saxes/issues/32#issuecomment-579943652) so I won't repeat them here.

(You'll note that saxes next version will have an `xmldecl` event, but alas as I mentioned earlier in this issue report, that does not help you get accurate location information *in all cases*.

So the ground-work to get better location information is there. I am personally pressed for time right now so I don't have time to work on adding the functionality for providing more refined information location.

Could someone *else* do it? Yes... but it is fraught with peril. I'm very keen on keeping the performance of saxes as good as it is now, or improve it. Someone could come along and just add logic to saxes that makes the event handlers be called with position information. The easy way to do it would be to just calculate positions all the time, but the problem with this is that it would have a significant performance impact that everyone would have to pay for, even those who don't need it. Flags could be added so that the information is maintained only when the user has indicated a need for it, but checking flags is also costly.

I've identified one way by which it should be possible to add position information for all event handlers, and have it cause a time cost at parsing only in those cases where the information is actually needed. It would require hooking into [`stateTable`](https://github.com/lddubeau/saxes/blob/master/src/saxes.ts#L728). The user wants to know where start and end tags start and end? Ok, replace the default state handlers that deal with start and end tags with handlers that record the necessary bookkeeping information and then call the original handlers (i.e. those that are put in the table by default when no location information is required). Doing this, however, is more difficult than the hypothetical approach in the previous paragraph because it requires understanding very well the internals of saxes.

Since you were thinking of submitting a PR, I thought I should bring you up to date on my thinking.

**Comment by wvbe** [comment]
Hey @lddubeau , thanks for this update! The `stateTable` approach doesn't sound too bad, but it's become apparent that besides a nicely _tested_ PR I should also gather some performance data, in order to assess the impact of said PR.

It'll probably be a while before this becomes a priority for me again, but who know what tickles me in the mean time. Also, looking forward to playing with the next release of saxes! Awesome work

All the best,
Wybe
